Cleanup.

diff --git a/ccat b/ccat
--- a/ccat
+++ b/ccat
@@ -9,19 +9,22 @@ IFS='
 '
 
 usage () {
-  echo "usage: $(basename "$0") [OPTION]... FILE"
-  echo ""
-  echo " -h   display this help and exit"
+  cat << EOF
+usage: $(basename "$0") [OPTION]... FILE
+
+options:
+  -h    display this help and exit
+EOF
 }
 
 while getopts "h" opt; do
   case "$opt" in
     h)
-      usage
+      usage >&1
       exit 0
       ;;
     \?)
-      usage
+      usage >&2
       exit 1
       ;;
   esac
@@ -31,19 +34,18 @@ shift $((OPTIND-1))
 
 file="$1"
 
-if ! `which pygmentize >/dev/null 2>&1`; then
-  echo "pygmentize not found"
-  echo "easy_install it"
+if ! which pygmentize >/dev/null 2>&1; then
+  printf "pygmentize not found.\neasy_install it.\n" >&2
   exit 127
 fi
 
 if [ -z "$file" ]; then
   file=/dev/stdin
-elif [ ! -e $1 ]; then
-  echo "$(basename "$0"): ${file}: No such file or directory"
+elif [ ! -e "$1" ]; then
+  printf "%s: %s: No such file or directory" "$(basename "$0")" "$file" >&2
   exit 2
 elif [ -d "$file" ]; then
-  echo "$(basename "$0"): ${file}: Is a directory "
+  printf "%s: %s: Is a directory" "$(basename "$0")" "$file" >&2
   exit 2
 fi
 
diff --git a/fsize b/fsize
--- a/fsize
+++ b/fsize
@@ -1,5 +1,54 @@
 #!/bin/sh
 
+# exit if command fails
+set -e
+# sane behaviour for cd
+unset CDPATH
+# set IFS to SP HT LF.
+IFS=' 	
+'
+
+usage () {
+  cat << EOF
+usage: $(basename "$0") [OPTIONS].. [SIZE] [FACE]
+
+Change the font of the current terminal to SIZE and FACE.
+SIZE default: 12
+FACE default: medium
+
+FACE:
+  - bold
+  - italic
+  - bolditalic or italicbold
+
+options:
+  -h    display this help and exit.
+EOF
+}
+
+while getopts "h" opt; do
+  case "$opt" in
+    h)
+      usage >&1
+      exit 0
+      ;;
+    \?)
+      usage >&2
+      exit 1
+      ;;
+  esac
+done
+
+shift $((OPTIND-1))
+
+if [ ! -t 1 ]; then
+  printf "stdin: is not a tty\n" >&2
+fi
+
+if [ "$SHELL" != "$(which bash)" ]; then
+  printf "stdin: is not bash\n" >&2
+fi
+
 if [ -z "${1+x}" ]; then
   size="12"
 else
@@ -7,16 +56,16 @@ else
 fi
 
 if [ -z "${2+x}" ]; then
-    face="medium"
+  face="medium"
 else
-    case $2 in
-        bold) face="bold" ;;
-        italic) face="italic" ;;
-        bolditalic) face="bold:italic" ;;
-        *) face="medium" ;;
-    esac
+  case "$2" in
+    bold) face="bold" ;;
+    italic) face="italic" ;;
+    bolditalic|italicbold) face="bold:italic" ;;
+    *) face="medium" ;;
+  esac
 fi
 
-printf '\33]50;%s%s%s%d\007' "xft:Inconsolata:" "${face}" ":autohint=true:antialias=true:pixelsize=" "${size}"
+printf '\33]50;%s:%s:%s%d\007' "xft:Inconsolata" "${face}" "autohint=true:antialias=true:pixelsize=" "${size}"
 
 # vim: ft=sh ts=2 sts=2 sw=2 et:
