Cleanup mkscript

diff --git a/mkscript b/mkscript
--- a/mkscript
+++ b/mkscript
@@ -1,7 +1,7 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
 function usage() {
-    echo "Usage: mkscript [OPTIONS]... FILE
+  echo "Usage: $(basename "$0") [OPTIONS]... FILE
 
 Creates a new script file and adds a header to the file according to the file \
 exenstion.
@@ -9,107 +9,111 @@ If a template.\"type\" exists in ~/Templates, the content of this file will be \
 used as content for the new created script file.
 Makes the script file executeable.
 
-  -t  type of the script file, must be the file extension
-  -n  make the created file NOT executeable
-  -h  display this help and exit"
+  -t <type>   type of the script file, must be the file extension
+  -n          make the created file NOT executeable
+  -h          display this help and exit"
 }
 
 filename=""
 type_to_create=""
 make_exec=1
 
-while getopts :t:nh OPT; do
-    case "$OPT" in
-        t) type_to_create=$OPTARG ;;
-        n) make_exec=0 ;;
-        h) usage ; exit 0 ;;
-        \?) usage ; exit 1 ;;
-    esac
+while getopts ":t:nh" opt; do
+  case "$opt" in
+    t) type_to_create=$OPTARG ;;
+    n) make_exec=0 ;;
+    h) usage ; exit 0 ;;
+    \?) usage ; exit 1 ;;
+  esac
 done
 
-shift `expr $OPTIND - 1`
+shift $((OPTIND-1))
 
 [ $# -eq 0 ] && { usage ; exit 1 ; }
 
 filename="$1"
 
-[ -z "$type_to_create" ] && type_to_create="$(echo $filename |awk -F . '{if (NF>1) {print $NF}}')"
+[ -z "$type_to_create" ] && type_to_create="$(echo "$filename" |awk -F . '{if (NF>1) {print $NF}}')"
 [ -z "$type_to_create" ] && { echo "No type found" ; exit 1 ; }
-[ -f $filename ] && { echo "File '$filename' already exists." ; exit 2 ; }
+[ -f "$filename" ] && { echo "File '$filename' already exists." ; exit 2 ; }
 
 template="${HOME}/Templates/template.${type_to_create}"
 
 if [ -f "$template" ]; then
-    cat "$template" >> $filename
+  cat "$template" >> "$filename"
 else
-    case $type_to_create in
-        py)
-            echo '#!/usr/bin/env python' >> $filename
-            echo '# -*- coding: utf-8 -*-'>> $filename
-            echo >> $filename
-            echo 'import os' >> $filename
-            echo 'import sys' >> $filename
-            echo >> $filename
-            ;;
+  case "$type_to_create" in
+    py)
+      echo '#!/usr/bin/env python' >> "$filename"
+      echo '# -*- coding: utf-8 -*-' >> "$filename"
+      echo '# pylint: disable=invalid-name' >> "$filename"
+      echo >> "$filename"
+      echo 'import os' >> "$filename"
+      echo 'import sys' >> "$filename"
+      echo >> "$filename"
+      echo >> "$filename"
+      echo '# vim: ft=python ts=2 sts=2 sw=2 et:' >> "$filename"
+      ;;
 
-        pl)
-            echo '#!/usr/bin/env perl' >> $filename
-            echo >> $filename
-            echo 'use warnings;' >> $filename
-            echo 'use strict;' >> $filename
-            echo >> $filename
-            ;;
+    pl)
+      echo '#!/usr/bin/env perl' >> "$filename"
+      echo >> "$filename"
+      echo 'use warnings;' >> "$filename"
+      echo 'use strict;' >> "$filename"
+      echo >> "$filename"
+      ;;
 
-        sh)
-            echo '#!/usr/bin/env sh' >> $filename
-            echo >> $filename
-            echo >> $filename
-            ;;
+    sh)
+      echo '#!/usr/bin/env sh' >> "$filename"
+      echo >> "$filename"
+      echo >> "$filename"
+      echo '# vim: ft=sh ts=2 sts=2 sw=2 et:' >> "$filename"
+      ;;
 
-        bash)
-            echo '#!/usr/bin/env bash' >> $filename
-            echo >> $filename
-            echo >> $filename
-            echo "# vim: ft=sh:" >> $filename
-            ;;
+    bash)
+      echo '#!/usr/bin/env bash' >> "$filename"
+      echo >> "$filename"
+      echo >> "$filename"
+      echo '# vim: ft=sh ts=2 sts=2 sw=2 et:' >> "$filename"
+      ;;
 
-        scm)
-            echo '#!/usr/bin/env guile' >> $filename
-            echo '!#' >> $filename
-            echo >> $filename
-            echo >> $filename
-            ;;
+    scm)
+      echo '#!/usr/bin/env guile' >> "$filename"
+      echo '!#' >> "$filename"
+      echo >> "$filename"
+      echo >> "$filename"
+      ;;
 
-        tex)
-            echo '\documentclass[11pt]{article}' >> $filename
-            echo '\title{}' >> $filename
-            echo '\author{<your name here>}' >> $filename
-            echo '\begin{document}' >> $filename
-            echo '\maketitle' >> $filename
-            echo '\section{}' >> $filename
-            echo '\end{document}' >> $filename
-            echo >> $filename
-            ;;
+    tex)
+      echo '\documentclass[11pt]{article}' >> "$filename"
+      echo '\title{}' >> "$filename"
+      echo '\author{<your name here>}' >> "$filename"
+      echo '\begin{document}' >> "$filename"
+      echo '\maketitle' >> "$filename"
+      echo '\section{}' >> "$filename"
+      echo '\end{document}' >> "$filename"
+      echo >> "$filename"
+      ;;
 
-        c)
-            echo '#include <stdio.h>' >> $filename
-            echo '#include <stdlib.h>' >> $filename
-            echo >> $filename
-            echo 'int' >> $filename
-            echo 'main(int argc, char **argv)' >> $filename
-            echo '{' >> $filename
-            echo -e "\texit(EXIT_SUCCESS);" >> $filename
-            echo '}' >> $filename
-            ;;
+    c)
+      echo '#include <stdio.h>' >> "$filename"
+      echo '#include <stdlib.h>' >> "$filename"
+      echo >> "$filename"
+      echo 'int' >> "$filename"
+      echo 'main(int argc, char *argv[])' >> "$filename"
+      echo '{' >> "$filename"
+      echo -e "\texit(EXIT_SUCCESS);" >> "$filename"
+      echo '}' >> "$filename"
+      ;;
 
-        *)
-            echo "Unknown script type $type_to_create"
-            exit 3
-            ;;
-    esac
+    *)
+      echo "Unknown script type $type_to_create"
+      exit 3
+      ;;
+  esac
 fi
 
-[ -f $filename ] && [ $make_exec -eq 1 ] && chmod u+x $filename
+[ -f "$filename" ] && [ "$make_exec" -eq 1 ] && chmod ugo+x "$filename"
+exit $?
 
-exit 0
-
+# vim: ft=sh ts=2 sts=2 sw=2 et:
